
var lootItems =  Array(
    
    "Abacus - 2gp, 2lb. ",
    "Acid (vial) - 25 gp, 1lb",
    "Alchemist’s fire (flask) - 50 gp, 1lb ",
    "Arrows (20) ",
    "Arrows (10) ",
    "Blowgun needles (10)",
    "Crossbow bolts (10)",
    "Sling bullets (10)",
    "Arrows (5) ",
    "Blowgun needles (5)",
    "Crossbow bolts (5)",
    "Sling bullets (5)",
    "Antitoxin (vial)",
    "Arcane focus - Crystal",
    "Arcane focus - Orb",
    "Arcane focus - Rod",
    "Arcane focus - Staff",
    "Arcane focus - Wand ",
    "Backpack ",
    "Ball bearings (bag of 1,000) ",
    "Barrel ",
    "Basket ",
    "Bedroll ",
    "Bell ",
    "Blanket ",
    "Block and tackle ",
    "Book ",
    "Glass Bottle ",
    "Bucket ",
    "Caltrops (bag of 20) ",
    "Candle ",
    "Crossbow bolt case ",
    "Case, map or scroll ",
    "Chain (10 feet) ",
    "Chalk (1 piece) ",
    "Chest",
    "Climber's kit ",
    "Clothes, common",
    "Clothes, costume ",
    "Clothes, fine ",
    "Clothes, traveler’s ",
    "Component pouch ",
    "Crowbar ",
    "Druidic focus - Sprig of mistletoe ",
    "Druidic focus - Totem ",
    "Druidic focus - Wooden staff ",
    "Druidic focus - Yew wand ",
    "Fishing tackle ",
    "Flask or tankard ",
    "Grappling hook ",
    "Hammer ",
    "Hammer, sledge ",
    "Healer’s kit ",
    "Holy symbol - Reliquary ",
    "Holy symbol - Emblem ",
    "Holy symbol - Amulet ",
    "Holy water (flask) ",
    "Hourglass ",
    "Hunting trap ",
    "Ink (1 ounce bottle) ",
    "Ink pen ",
    "Jug or pitcher ",
    "Ladder (10-foot) ",
    "Lamp ",
    "Lantern, bullseye ",
    "Lantern, hooded ",
    "Magnifying Glass ",
    "Manacles ",
    "Messkit ",
    "Mirror, steel ",
    "Oil (flask) ",
    "Paper (one sheet) ",
    "Parchment (one sheet) ",
    "Perfume (vial)",
    "Pick, miner’s ",
    "Piton ",
    "Poison, basic (vial) ",
    "Pole (10-foot) ",
    "Iron Pot ",
    "Potion of healing ",
    "Pouch",
    "Quiver ",
    "Ram, portable ",
    "Rations (1 day) ",
    "Robes",
    "Rope, hempen (50 feet) ",
    "Rope, silk (50 feet) ",
    "Sack",
    "Scale, merchant’s ",
    "Sealing wax ",
    "Shovel ",
    "Signal whistle ",
    "Signet ring ",
    "Soap ",
    "Spellbook ",
    "Spikes, iron (10) ",
    "Spyglass ",
    "Tent, two-person ",
    "Tinderbox ",
    "Torch ",
    "Vial ",
    "Waterskin ",
    "Whetstone ",
    "Drum ",
    "Flute ",
    "Lute",
    "Horn ",
    "Pan flute ",
    "Keg of ale ",
    "Jug of ale ",
    "Bottle of ale",
    "Botle of wine (common)",
    "Bottle of wine (fine)",
    "Loaf of bread",
    "Cheese wedge",
    "Cheese wheel"
    
)

export default lootItems;