var lootItems =  Array(
    "Club",
    "Dagger",
    "Greatclub",
    "Handaxe ",
    "Javelin ",
    "Light Hammer ",
    "Mace ",
    "Quaterstaff ",
    "Sickle ",
    "Spear ",
    "Light Crossbow ",
    "Dart (10) ",
    "Shortbow ",
    "Sling ",
    "Battleaxe ",
    "Flail ",
    "Glaive ",
    "Greataxe ",
    "Halbard ",
    "Lance ",
    "Longsword ",
    "Moringstar ",
    "Pike ",
    "Rapier ",
    "Shortsword ",
    "Trident ",
    "Warpick ",
    "Warhammer ",
    "Whip ",
    "Blowgun ",
    "Hand Crossbow ",
    "Heavy Crossbow ",
    "Longbow ",
    "Net ",
    "Sabre - 1d6, slashing, Versitile(1d8)  ",
    "Spiked Maul - 1d8 bludgeoning	 ",
    "Kartana - 1d8 slashing, Versitile(1d10)  ",
    "Boomarang -  1d4 bludgeoning, Returning",
    "Bladed-Staff - 1d8 slashing, Versatile(1d8 bludgeoning) ",
    "Broad sword - 2d4 slashing/piercing "
    )
    
    export default lootItems;